apiVersion: v1
kind: ConfigMap
metadata:
  name: sm-config
  namespace: sm
  labels:
    app: sm-config
data:
  SERVER_PORT: "18001"
  MANAGEMENT_SERVER_PORT: "15001"
  MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE: "*"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:password@mongovirt:27017/restaurantdb?authSource=admin&readPreference=primary&ssl=false"
