apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: sm
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: blitznihar/mongorestaurant
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 27017