apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sm
spec:
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: nginxdebug
        image: nginx
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
