apiVersion: v1
kind: Service
metadata:
  name: springmongo-service
  namespace: sm
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: actualservice-18001
    port: 18001
    targetPort: 18001
    nodePort: 30001
  - name: actuatorservice-15001
    port: 15001
    targetPort: 15001
    nodePort: 30002