apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapi-deployment
  namespace: sm
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: dbreceipesformongo
        image: blitznihar/dbreceipesformongo
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 18001
        - containerPort: 15001
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 15001
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 15001
          initialDelaySeconds: 60
          periodSeconds: 5
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: sm-config
              key: SERVER_PORT
        - name: MANAGEMENT_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: sm-config
              key: MANAGEMENT_SERVER_PORT
        - name: MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE
          valueFrom:
            configMapKeyRef:
              name: sm-config
              key: MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: sm-config
              key: SPRING_DATA_MONGODB_URI